; PZEM004T_Enhanced - Exemple ESP32
; Compilation : pio run -d examples/PZEM_ESP32
; (ou : cd examples/PZEM_ESP32 && pio run)

[platformio]
src_dir = .

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = file://../..
