; PZEM004T_Enhanced - Exemple HardwareSerial
; Compilation : pio run -d examples/PZEM_HardwareSerial
; (ou : cd examples/PZEM_HardwareSerial && pio run)

[platformio]
src_dir = .

[env:mega]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = file://../..

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = file://../..
